### ISSUE TITLE
mpd fails in v2.1.0.

### ISSUE THREAD

**Issue by Lacanbonda** [devine-dl/devine#46] opened 2023-03-24 11:19 UTC
BUG:
Hello, in v2.1.0 mpd which has  4k content is not getting downloaded only it lists and exit with error but the same content with only 1080p mpd works perfectly. the error related to keyid as the full trace think so. below attached screenshot of last out of the error.

**Screenshots**
https://i.ibb.co/RSDf0JZ/Screenshot-186.png

**Additional context**
but its still works in v2.0.1 both 1080p and 4k mpd's perfectly.

**Comment by rlaphoenix** [comment] 2023-03-24 12:16
The full error log is required. However, it looks like this might be an error with your WVD file being outdated. Use `pywidevine migrate`. This issue may be a duplicate of #45

**Comment by Lacanbonda** [comment] 2023-03-24 13:47
1 Video
     └── [H.265, DV] | hi | 960x540 @ 1038 kb/s, 25.000 FPS
         ⠙ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ • --:-- • -
     1 Audio
     └── [DD+] | 6.0 | 257 kb/s | ta
         ⠙ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ • --:-- • -
     1 Subtitle
     └── [VTT] | en
          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ • 00:00 • 1.9MiB/s

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:2696   │
│ in _parse                                                                    │
│                                                                              │
│   2693 │   def _parse(self, stream, context, path):                          │
│   2694 │   │   try:                                                          │
│   2695 │   │   │   path += " -> %s" % (self.name)                            │
│ ❱ 2696 │   │   │   return self.subcon._parse(stream, context, path)          │
│   2697 │   │   except ConstructError as e:                                   │
│   2698 │   │   │   if "\n" in str(e):                                        │
│   2699 │   │   │   │   raise                                                 │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:1881   │
│ in _parse                                                                    │
│                                                                              │
│   1878 │   def _parse(self, stream, context, path):                          │
│   1879 │   │   obj = self.subcon._parse(stream, context, path)               │
│   1880 │   │   if obj != self.value:                                         │
│ ❱ 1881 │   │   │   raise ConstError("expected %r but parsed %r" % (self.valu │
│   1882 │   │   return obj                                                    │
│   1883 │   def _build(self, obj, stream, context, path):                     │
│   1884 │   │   if obj not in (None, self.value):                             │
╰──────────────────────────────────────────────────────────────────────────────╯
ConstError: expected 0 but parsed 1

During handling of the above exception, another exception occurred:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ D:\Tools\scripts\dev\devine\devine\commands\dl.py:482 in result              │
│                                                                              │
│   479 │   │   │   │   │   │   │   │   )                                      │
│   480 │   │   │   │   │   │   │   │   for i, track in enumerate(title.tracks │
│   481 │   │   │   │   │   │   │   )):                                        │
│ ❱ 482 │   │   │   │   │   │   │   │   download.result()                      │
│   483 │   │   │   │   except KeyboardInterrupt:                              │
│   484 │   │   │   │   │   console.print(Padding(                             │
│   485 │   │   │   │   │   │   ":x: Download Cancelled...",                   │
│                                                                              │
│ C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \_base.py:438 in result                                                      │
│                                                                              │
│   435 │   │   │   │   if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]: │
│   436 │   │   │   │   │   raise CancelledError()                             │
│   437 │   │   │   │   elif self._state == FINISHED:                          │
│ ❱ 438 │   │   │   │   │   return self.__get_result()                         │
│   439 │   │   │   │                                                          │
│   440 │   │   │   │   self._condition.wait(timeout)                          │
│   441                                                                        │
│                                                                              │
│ C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \_base.py:390 in __get_result                                                │
│                                                                              │
│   387 │   def __get_result(self):                                            │
│   388 │   │   if self._exception:                                            │
│   389 │   │   │   try:                                                       │
│ ❱ 390 │   │   │   │   raise self._exception                                  │
│   391 │   │   │   finally:                                                   │
│   392 │   │   │   │   # Break a reference cycle with the exception in self._ │
│   393 │   │   │   │   self = None                                            │
│                                                                              │
│ C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \thread.py:52 in run                                                         │
│                                                                              │
│    49 │   │   │   return                                                     │
│    50 │   │                                                                  │
│    51 │   │   try:                                                           │
│ ❱  52 │   │   │   result = self.fn(*self.args, **self.kwargs)                │
│    53 │   │   except BaseException as exc:                                   │
│    54 │   │   │   self.future.set_exception(exc)                             │
│    55 │   │   │   # Break a reference cycle with the exception 'exc'         │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\commands\dl.py:779 in download_track      │
│                                                                              │
│   776 │   │   │   │   │   license_widevine=prepare_drm                       │
│   777 │   │   │   │   )                                                      │
│   778 │   │   │   elif track.descriptor == track.Descriptor.MPD:             │
│ ❱ 779 │   │   │   │   DASH.download_track(                                   │
│   780 │   │   │   │   │   track=track,                                       │
│   781 │   │   │   │   │   save_path=save_path,                               │
│   782 │   │   │   │   │   save_dir=save_dir,                                 │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\manifests\dash.py:369 in             │
│ download_track                                                               │
│                                                                              │
│   366 │   │   │   │   │   ))                                                 │
│   367 │   │   │   │   │   res.raise_for_status()                             │
│   368 │   │   │   │   │   init_data = res.content                            │
│ ❱ 369 │   │   │   │   │   track_kid = track.get_key_id(init_data)            │
│   370 │   │   │   │                                                          │
│   371 │   │   │   │   if segment_timeline is not None:                       │
│   372 │   │   │   │   │   seg_time_list = []                                 │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\tracks\track.py:123 in get_key_id    │
│                                                                              │
│   120 │   │   │   │   │   return UUID(bytes=base64.b64decode(enc_key_id))    │
│   121 │   │                                                                  │
│   122 │   │   # look for track encryption mp4 boxes                          │
│ ❱ 123 │   │   for tenc in get_boxes(init_data, b"tenc"):                     │
│   124 │   │   │   if tenc.key_ID.int != 0:                                   │
│   125 │   │   │   │   return tenc.key_ID                                     │
│   126                                                                        │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\utilities.py:145 in get_boxes        │
│                                                                              │
│   142 │   │   │   index -= 4  # size is before box type and is 4 bytes long  │
│   143 │   │   data = data[index:]                                            │
│   144 │   │   try:                                                           │
│ ❱ 145 │   │   │   box = Box.parse(data)                                      │
│   146 │   │   except IOError:                                                │
│   147 │   │   │   # TODO: Does this miss any data we may need?               │
│   148 │   │   │   break                                                      │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:175 in │
│ parse                                                                        │
│                                                                              │
│    172 │   │                                                                 │
│    173 │   │   Strings, buffers, memoryviews, and other complete buffers can │
│    174 │   │   """                                                           │
│ ❱  175 │   │   return self.parse_stream(BytesIO(data), context, **kw)        │
│    176 │                                                                     │
│    177 │   def parse_stream(self, stream, context=None, **kw):               │
│    178 │   │   """                                                           │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:186 in │
│ parse_stream                                                                 │
│                                                                              │
│    183 │   │   if context is None:                                           │
│    184 │   │   │   context = Container()                                     │
│    185 │   │   context.update(kw)                                            │
│ ❱  186 │   │   return self._parse(stream, context, "parsing")                │
│    187 │                                                                     │
│    188 │   def _parse(self, stream, context, path):                          │
│    189 │   │   """                                                           │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\pymp4\parser.py:46 in    │
│ _parse                                                                       │
│                                                                              │
│    43 │   │   │   lengthfield_size = stream.tell() - offset_start            │
│    44 │   │                                                                  │
│    45 │   │   stream2 = BoundBytesIO(stream, length - lengthfield_size)      │
│ ❱  46 │   │   obj = self.subcon._parse(stream2, context, path)               │
│    47 │   │   return obj                                                     │
│    48 │                                                                      │
│    49 │   def _build(self, obj, stream, context, path):                      │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:855 in │
│ _parse                                                                       │
│                                                                              │
│    852 │   │   context = Container(_ = context)                              │
│    853 │   │   for i,sc in enumerate(self.subcons):                          │
│    854 │   │   │   if sc.flagembedded:                                       │
│ ❱  855 │   │   │   │   subobj = list(sc._parse(stream, context, path).items( │
│    856 │   │   │   │   obj.update(subobj)                                    │
│    857 │   │   │   │   context.update(subobj)                                │
│    858 │   │   │   else:                                                     │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:297 in │
│ _parse                                                                       │
│                                                                              │
│    294 │   │   self.subcon = subcon                                          │
│    295 │   │   self._inherit_flags(subcon)                                   │
│    296 │   def _parse(self, stream, context, path):                          │
│ ❱  297 │   │   return self.subcon._parse(stream, context, path)              │
│    298 │   def _build(self, obj, stream, context, path):                     │
│    299 │   │   return self.subcon._build(obj, stream, context, path)         │
│    300 │   def _sizeof(self, context, path):                                 │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:1544   │
│ in _parse                                                                    │
│                                                                              │
│   1541 │   │   self.includekey = includekey                                  │
│   1542 │   def _parse(self, stream, context, path):                          │
│   1543 │   │   key = self.keyfunc(context) if callable(self.keyfunc) else se │
│ ❱ 1544 │   │   obj = self.cases.get(key, self.default)._parse(stream, contex │
│   1545 │   │   if self.includekey:                                           │
│   1546 │   │   │   return key, obj                                           │
│   1547 │   │   else:                                                         │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:859 in │
│ _parse                                                                       │
│                                                                              │
│    856 │   │   │   │   obj.update(subobj)                                    │
│    857 │   │   │   │   context.update(subobj)                                │
│    858 │   │   │   else:                                                     │
│ ❱  859 │   │   │   │   subobj = sc._parse(stream, context, path)             │
│    860 │   │   │   │   if sc.name is not None:                               │
│    861 │   │   │   │   │   obj[sc.name] = subobj                             │
│    862 │   │   │   │   │   context[sc.name] = subobj                         │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:2700   │
│ in _parse                                                                    │
│                                                                              │
│   2697 │   │   except ConstructError as e:                                   │
│   2698 │   │   │   if "\n" in str(e):                                        │
│   2699 │   │   │   │   raise                                                 │
│ ❱ 2700 │   │   │   raise e.__class__("%s\n    %s" % (e, path))               │
│   2701 │   def _build(self, obj, stream, context, path):                     │
│   2702 │   │   try:                                                          │
│   2703 │   │   │   path += " -> %s" % (self.name)                            │
╰──────────────────────────────────────────────────────────────────────────────╯
ConstError: expected 0 but parsed 1
    parsing -> version

**Comment by rlaphoenix** [comment] 2023-03-26 21:15
It looks like an error occurred when parsing the init segment of the 4K track, which it tries to get to retrieve the track's Key ID. It seems like it failed to parse a specific box. Could you open `D:\Tools\scripts\dev\devine\devine\core\utilities.py` and go to the function `def get_boxes`. Edit it to the following:

```diff
def get_boxes(data: bytes, box_type: bytes, as_bytes: bool = False) -> Box:
    """Scan a byte array for a wanted box, then parse and yield each find."""
    # using slicing to get to the wanted box is done because parsing the entire box and recursively
    # scanning through each box and its children often wouldn't scan far enough to reach the wanted box.
    # since it doesnt care what child box the wanted box is from, this works fine.
    if not isinstance(data, (bytes, bytearray)):
        raise ValueError("data must be bytes")
    while True:
        try:
            index = data.index(box_type)
        except ValueError:
            break
        if index < 0:
            break
        if index > 4:
            index -= 4  # size is before box type and is 4 bytes long
        data = data[index:]
        try:
+            with open(r"D:\Tools\scripts\dev\devine\INIT_SEGMENT_DUMP.bin", "wb") as f:
+                f.write(data)
            box = Box.parse(data)
        except IOError:
            # TODO: Does this miss any data we may need?
            break
        if as_bytes:
            box = Box.build(box)
        yield box
```

Once done re-run and try to have the error occur again. Once it occurs can you send me the file at `D:\Tools\scripts\dev\devine\INIT_SEGMENT_DUMP.bin`? Once done I can analyze the file, see where exactly it's failing, and what box is failing, then update pymp4.

**Comment by Lacanbonda** [comment] 2023-03-27 03:10
INIT_SEGMENT_DUMP.bin: https://file.io/oPW7oRA6h1Cm

**Comment by Lacanbonda** [comment] 2023-03-28 04:15
![Screenshot_188](https://user-images.githubusercontent.com/105432999/228126424-d36a0494-ffd0-472b-bd99-664f683d41ee.png)
Video got failed!. with rlaphoenix-pymp4 = "^1.5.0"

error log:
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:2696   │
│ in _parse                                                                    │
│                                                                              │
│   2693 │   def _parse(self, stream, context, path):                          │
│   2694 │   │   try:                                                          │
│   2695 │   │   │   path += " -> %s" % (self.name)                            │
│ ❱ 2696 │   │   │   return self.subcon._parse(stream, context, path)          │
│   2697 │   │   except ConstructError as e:                                   │
│   2698 │   │   │   if "\n" in str(e):                                        │
│   2699 │   │   │   │   raise                                                 │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:1881   │
│ in _parse                                                                    │
│                                                                              │
│   1878 │   def _parse(self, stream, context, path):                          │
│   1879 │   │   obj = self.subcon._parse(stream, context, path)               │
│   1880 │   │   if obj != self.value:                                         │
│ ❱ 1881 │   │   │   raise ConstError("expected %r but parsed %r" % (self.valu │
│   1882 │   │   return obj                                                    │
│   1883 │   def _build(self, obj, stream, context, path):                     │
│   1884 │   │   if obj not in (None, self.value):                             │
╰──────────────────────────────────────────────────────────────────────────────╯
ConstError: expected 0 but parsed 25

During handling of the above exception, another exception occurred:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ D:\Tools\scripts\dev\devine\devine\commands\dl.py:505 in result              │
│                                                                              │
│    502 │   │   │   │   │   │   │   │   )                                     │
│    503 │   │   │   │   │   │   │   │   for i, track in enumerate(title.track │
│    504 │   │   │   │   │   │   │   )):                                       │
│ ❱  505 │   │   │   │   │   │   │   │   download.result()                     │
│    506 │   │   │   │   except KeyboardInterrupt:                             │
│    507 │   │   │   │   │   console.print(Padding(                            │
│    508 │   │   │   │   │   │   ":x: Download Cancelled...",                  │
│                                                                              │
│ C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \_base.py:438 in result                                                      │
│                                                                              │
│   435 │   │   │   │   if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]: │
│   436 │   │   │   │   │   raise CancelledError()                             │
│   437 │   │   │   │   elif self._state == FINISHED:                          │
│ ❱ 438 │   │   │   │   │   return self.__get_result()                         │
│   439 │   │   │   │                                                          │
│   440 │   │   │   │   self._condition.wait(timeout)                          │
│   441                                                                        │
│                                                                              │
│ C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \_base.py:390 in __get_result                                                │
│                                                                              │
│   387 │   def __get_result(self):                                            │
│   388 │   │   if self._exception:                                            │
│   389 │   │   │   try:                                                       │
│ ❱ 390 │   │   │   │   raise self._exception                                  │
│   391 │   │   │   finally:                                                   │
│   392 │   │   │   │   # Break a reference cycle with the exception in self._ │
│   393 │   │   │   │   self = None                                            │
│                                                                              │
│ C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \thread.py:52 in run                                                         │
│                                                                              │
│    49 │   │   │   return                                                     │
│    50 │   │                                                                  │
│    51 │   │   try:                                                           │
│ ❱  52 │   │   │   result = self.fn(*self.args, **self.kwargs)                │
│    53 │   │   except BaseException as exc:                                   │
│    54 │   │   │   self.future.set_exception(exc)                             │
│    55 │   │   │   # Break a reference cycle with the exception 'exc'         │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\commands\dl.py:860 in download_track      │
│                                                                              │
│    857 │   │   │   │   │   license_widevine=prepare_drm                      │
│    858 │   │   │   │   )                                                     │
│    859 │   │   │   elif track.descriptor == track.Descriptor.MPD:            │
│ ❱  860 │   │   │   │   DASH.download_track(                                  │
│    861 │   │   │   │   │   track=track,                                      │
│    862 │   │   │   │   │   save_path=save_path,                              │
│    863 │   │   │   │   │   save_dir=save_dir,                                │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\manifests\dash.py:369 in             │
│ download_track                                                               │
│                                                                              │
│   366 │   │   │   │   │   ))                                                 │
│   367 │   │   │   │   │   res.raise_for_status()                             │
│   368 │   │   │   │   │   init_data = res.content                            │
│ ❱ 369 │   │   │   │   │   track_kid = track.get_key_id(init_data)            │
│   370 │   │   │   │                                                          │
│   371 │   │   │   │   if segment_timeline is not None:                       │
│   372 │   │   │   │   │   seg_time_list = []                                 │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\tracks\track.py:123 in get_key_id    │
│                                                                              │
│   120 │   │   │   │   │   return UUID(bytes=base64.b64decode(enc_key_id))    │
│   121 │   │                                                                  │
│   122 │   │   # look for track encryption mp4 boxes                          │
│ ❱ 123 │   │   for tenc in get_boxes(init_data, b"tenc"):                     │
│   124 │   │   │   if tenc.key_ID.int != 0:                                   │
│   125 │   │   │   │   return tenc.key_ID                                     │
│   126                                                                        │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\utilities.py:145 in get_boxes        │
│                                                                              │
│   142 │   │   │   index -= 4  # size is before box type and is 4 bytes long  │
│   143 │   │   data = data[index:]                                            │
│   144 │   │   try:                                                           │
│ ❱ 145 │   │   │   box = Box.parse(data)                                      │
│   146 │   │   except IOError:                                                │
│   147 │   │   │   # TODO: Does this miss any data we may need?               │
│   148 │   │   │   break                                                      │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:175 in │
│ parse                                                                        │
│                                                                              │
│    172 │   │                                                                 │
│    173 │   │   Strings, buffers, memoryviews, and other complete buffers can │
│    174 │   │   """                                                           │
│ ❱  175 │   │   return self.parse_stream(BytesIO(data), context, **kw)        │
│    176 │                                                                     │
│    177 │   def parse_stream(self, stream, context=None, **kw):               │
│    178 │   │   """                                                           │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:186 in │
│ parse_stream                                                                 │
│                                                                              │
│    183 │   │   if context is None:                                           │
│    184 │   │   │   context = Container()                                     │
│    185 │   │   context.update(kw)                                            │
│ ❱  186 │   │   return self._parse(stream, context, "parsing")                │
│    187 │                                                                     │
│    188 │   def _parse(self, stream, context, path):                          │
│    189 │   │   """                                                           │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\pymp4\parser.py:50 in    │
│ _parse                                                                       │
│                                                                              │
│    47 │   │   │   stream.seek(curr_pos)                                      │
│    48 │   │   │   length = eof - curr_pos + lengthfield_size                 │
│    49 │   │   stream2 = BoundBytesIO(stream, length - lengthfield_size)      │
│ ❱  50 │   │   obj = self.subcon._parse(stream2, context, path)               │
│    51 │   │   return obj                                                     │
│    52 │                                                                      │
│    53 │   def _build(self, obj, stream, context, path):                      │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:855 in │
│ _parse                                                                       │
│                                                                              │
│    852 │   │   context = Container(_ = context)                              │
│    853 │   │   for i,sc in enumerate(self.subcons):                          │
│    854 │   │   │   if sc.flagembedded:                                       │
│ ❱  855 │   │   │   │   subobj = list(sc._parse(stream, context, path).items( │
│    856 │   │   │   │   obj.update(subobj)                                    │
│    857 │   │   │   │   context.update(subobj)                                │
│    858 │   │   │   else:                                                     │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:297 in │
│ _parse                                                                       │
│                                                                              │
│    294 │   │   self.subcon = subcon                                          │
│    295 │   │   self._inherit_flags(subcon)                                   │
│    296 │   def _parse(self, stream, context, path):                          │
│ ❱  297 │   │   return self.subcon._parse(stream, context, path)              │
│    298 │   def _build(self, obj, stream, context, path):                     │
│    299 │   │   return self.subcon._build(obj, stream, context, path)         │
│    300 │   def _sizeof(self, context, path):                                 │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:1544   │
│ in _parse                                                                    │
│                                                                              │
│   1541 │   │   self.includekey = includekey                                  │
│   1542 │   def _parse(self, stream, context, path):                          │
│   1543 │   │   key = self.keyfunc(context) if callable(self.keyfunc) else se │
│ ❱ 1544 │   │   obj = self.cases.get(key, self.default)._parse(stream, contex │
│   1545 │   │   if self.includekey:                                           │
│   1546 │   │   │   return key, obj                                           │
│   1547 │   │   else:                                                         │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:859 in │
│ _parse                                                                       │
│                                                                              │
│    856 │   │   │   │   obj.update(subobj)                                    │
│    857 │   │   │   │   context.update(subobj)                                │
│    858 │   │   │   else:                                                     │
│ ❱  859 │   │   │   │   subobj = sc._parse(stream, context, path)             │
│    860 │   │   │   │   if sc.name is not None:                               │
│    861 │   │   │   │   │   obj[sc.name] = subobj                             │
│    862 │   │   │   │   │   context[sc.name] = subobj                         │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:2700   │
│ in _parse                                                                    │
│                                                                              │
│   2697 │   │   except ConstructError as e:                                   │
│   2698 │   │   │   if "\n" in str(e):                                        │
│   2699 │   │   │   │   raise                                                 │
│ ❱ 2700 │   │   │   raise e.__class__("%s\n    %s" % (e, path))               │
│   2701 │   def _build(self, obj, stream, context, path):                     │
│   2702 │   │   try:                                                          │
│   2703 │   │   │   path += " -> %s" % (self.name)                            │
╰──────────────────────────────────────────────────────────────────────────────╯
ConstError: expected 0 but parsed 25
    parsing -> _reserved1

**Comment by rlaphoenix** [comment] 2023-03-28 13:18
Can you follow the same steps to get a new BIN file for debugging?

**Comment by Lacanbonda** [comment] 2023-03-29 04:14
[INIT_SEGMENT_DUMP.zip](https://github.com/devine-dl/devine/files/11096516/INIT_SEGMENT_DUMP.zip)

**Comment by Lacanbonda** [comment] 2023-03-30 04:55
still v2.0.1 is fine working with latest update of pymp4 and others.

**Comment by rlaphoenix** [comment] 2023-04-01 16:11
> [INIT_SEGMENT_DUMP.zip](https://github.com/devine-dl/devine/files/11096516/INIT_SEGMENT_DUMP.zip)

Hi, sorry for the late reply. This should be fixed in master. I dont think this init segment dump is the one that had the issue you posted the log for. Anyway, give the latest code a try and see if it works.

**Comment by Lacanbonda** [comment] 2023-04-02 03:14
![Screenshot_189](https://user-images.githubusercontent.com/105432999/229329146-19e41b1f-f4a5-42d0-82f2-44c3e2bbd652.png)
still the same. i think bin is from audio which is working.

**Comment by rlaphoenix** [comment] 2023-04-23 16:43
Hi, so an update here is this service seems to mix up the data of the `tenc` box with that of another type of box (usually `avc1`). This means the data in it would never be parseable without an error.

Due to this I've gone ahead and committed https://github.com/devine-dl/devine/commit/630832e434707ec84db6dcda305f00119022559d which will ignore `tenc` boxes that fail to parse and it will hope there's a 2nd `tenc` box that is correct (which there usually is).

Could you try as of that commit and see if that fixed the problem?

**Comment by rlaphoenix** [comment] 2023-04-23 21:52
Further update. I've fully fixed the parsing error `ConstError: expected 0 but parsed 25 parsing -> _reserved1` by completely redefining what `_reserved1` was. I've also fixed the initial parsing error `ConstError: expected 0 but parsed 1 parsing -> version`. It now fully supports both v0 and v1 tenc boxes therefore this issue is fixed. I have also confirmed that it has been fixed myself as well as had someone else try.

**Closed by rlaphoenix** 2023-04-23 21:52 UTC
Labels: bug, upstream

**Comment by Lacanbonda** [comment] 2023-04-25 02:43
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ D:\Tools\scripts\dev\devine\devine\commands\dl.py:506 in result              │
│                                                                              │
│    503 │   │   │   │   │   │   │   │   )                                     │
│    504 │   │   │   │   │   │   │   │   for i, track in enumerate(title.track │
│    505 │   │   │   │   │   │   │   )):                                       │
│ ❱  506 │   │   │   │   │   │   │   │   download.result()                     │
│    507 │   │   │   │   except KeyboardInterrupt:                             │
│    508 │   │   │   │   │   console.print(Padding(                            │
│    509 │   │   │   │   │   │   ":x: Download Cancelled...",                  │
│                                                                              │
│ C:\Users\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \_base.py:438 in result                                                      │
│                                                                              │
│   435 │   │   │   │   if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]: │
│   436 │   │   │   │   │   raise CancelledError()                             │
│   437 │   │   │   │   elif self._state == FINISHED:                          │
│ ❱ 438 │   │   │   │   │   return self.__get_result()                         │
│   439 │   │   │   │                                                          │
│   440 │   │   │   │   self._condition.wait(timeout)                          │
│   441                                                                        │
│                                                                              │
│ C:\Users\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \_base.py:390 in __get_result                                                │
│                                                                              │
│   387 │   def __get_result(self):                                            │
│   388 │   │   if self._exception:                                            │
│   389 │   │   │   try:                                                       │
│ ❱ 390 │   │   │   │   raise self._exception                                  │
│   391 │   │   │   finally:                                                   │
│   392 │   │   │   │   # Break a reference cycle with the exception in self._ │
│   393 │   │   │   │   self = None                                            │
│                                                                              │
│ C:\Users\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \thread.py:52 in run                                                         │
│                                                                              │
│    49 │   │   │   return                                                     │
│    50 │   │                                                                  │
│    51 │   │   try:                                                           │
│ ❱  52 │   │   │   result = self.fn(*self.args, **self.kwargs)                │
│    53 │   │   except BaseException as exc:                                   │
│    54 │   │   │   self.future.set_exception(exc)                             │
│    55 │   │   │   # Break a reference cycle with the exception 'exc'         │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\commands\dl.py:863 in download_track      │
│                                                                              │
│    860 │   │   │   │   │   license_widevine=prepare_drm                      │
│    861 │   │   │   │   )                                                     │
│    862 │   │   │   elif track.descriptor == track.Descriptor.MPD:            │
│ ❱  863 │   │   │   │   DASH.download_track(                                  │
│    864 │   │   │   │   │   track=track,                                      │
│    865 │   │   │   │   │   save_path=save_path,                              │
│    866 │   │   │   │   │   save_dir=save_dir,                                │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\manifests\dash.py:452 in             │
│ download_track                                                               │
│                                                                              │
│   449 │   │   │                                                              │
│   450 │   │   │   if track.drm:                                              │
│   451 │   │   │   │   # last chance to find the KID                          │
│ ❱ 452 │   │   │   │   track_kid = track_kid or track.get_key_id(url=segments │
│   453 │   │   │   │   # license and grab content keys                        │
│   454 │   │   │   │   drm = track.drm[0]  # just use the first supported DRM │
│   455 │   │   │   │   if isinstance(drm, Widevine):                          │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\tracks\track.py:110 in get_key_id    │
│                                                                              │
│   107 │   │   │   The Key ID as a UUID object, or None if the Key ID could n │
│   108 │   │   """                                                            │
│   109 │   │   if not init_data:                                              │
│ ❱ 110 │   │   │   init_data = self.get_init_segment(*args, **kwargs)         │
│   111 │   │   if not isinstance(init_data, bytes):                           │
│   112 │   │   │   raise TypeError(f"Expected init_data to be bytes, not {ini │
│   113                                                                        │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\tracks\track.py:189 in               │
│ get_init_segment                                                             │
│                                                                              │
│   186 │   │   │   if start > end:                                            │
│   187 │   │   │   │   raise ValueError(f"The start range cannot be greater t │
│   188 │   │   else:                                                          │
│ ❱ 189 │   │   │   size_test = session.head(url)                              │
│   190 │   │   │   if "Content-Length" in size_test.headers:                  │
│   191 │   │   │   │   content_length = int(size_test.headers["Content-Length │
│   192 │   │   │   │   # use whichever is smaller in case this is a full file │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\requests\sessions.py:622 │
│ in head                                                                      │
│                                                                              │
│   619 │   │   """                                                            │
│   620 │   │                                                                  │
│   621 │   │   kwargs.setdefault("allow_redirects", False)                    │
│ ❱ 622 │   │   return self.request("HEAD", url, **kwargs)                     │
│   623 │                                                                      │
│   624 │   def post(self, url, data=None, json=None, **kwargs):               │
│   625 │   │   r"""Sends a POST request. Returns :class:`Response` object.    │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\requests\sessions.py:587 │
│ in request                                                                   │
│                                                                              │
│   584 │   │   │   "allow_redirects": allow_redirects,                        │
│   585 │   │   }                                                              │
│   586 │   │   send_kwargs.update(settings)                                   │
│ ❱ 587 │   │   resp = self.send(prep, **send_kwargs)                          │
│   588 │   │                                                                  │
│   589 │   │   return resp                                                    │
│   590                                                                        │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\requests\sessions.py:695 │
│ in send                                                                      │
│                                                                              │
│   692 │   │   hooks = request.hooks                                          │
│   693 │   │                                                                  │
│   694 │   │   # Get the appropriate adapter to use                           │
│ ❱ 695 │   │   adapter = self.get_adapter(url=request.url)                    │
│   696 │   │                                                                  │
│   697 │   │   # Start time (approximately) of the request                    │
│   698 │   │   start = preferred_clock()                                      │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\requests\sessions.py:792 │
│ in get_adapter                                                               │
│                                                                              │
│   789 │   │   │   │   return adapter                                         │
│   790 │   │                                                                  │
│   791 │   │   # Nothing matches :-/                                          │
│ ❱ 792 │   │   raise InvalidSchema(f"No connection adapters were found for {u │
│   793 │                                                                      │
│   794 │   def close(self):                                                   │
│   795 │   │   """Closes all adapters and as such the session"""              │
╰──────────────────────────────────────────────────────────────────────────────╯
InvalidSchema: No connection adapters were found for
"('https://drm.sonyliv.com/CMAF/277b63148d22476da95f2e9f2c5b2fee/1678019880/4k-ddp-aac-v1/video/hev1/7/seg-1.m4s', None)"
