### ISSUE TITLE
video fails with rlaphoenix-pymp4 !

### ISSUE THREAD

**Issue by Lacanbonda** [devine-dl/devine#50] opened 2023-03-28 04:24 UTC
[Screenshot_188](https://user-images.githubusercontent.com/105432999/228126424-d36a0494-ffd0-472b-bd99-664f683d41ee.png)
Video got failed!. with rlaphoenix-pymp4 = "^1.5.0" and tried version 0 replace as your previous suggestion that also failed with same.

error log:
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:2696   │
│ in _parse                                                                    │
│                                                                              │
│   2693 │   def _parse(self, stream, context, path):                          │
│   2694 │   │   try:                                                          │
│   2695 │   │   │   path += " -> %s" % (self.name)                            │
│ ❱ 2696 │   │   │   return self.subcon._parse(stream, context, path)          │
│   2697 │   │   except ConstructError as e:                                   │
│   2698 │   │   │   if "\n" in str(e):                                        │
│   2699 │   │   │   │   raise                                                 │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:1881   │
│ in _parse                                                                    │
│                                                                              │
│   1878 │   def _parse(self, stream, context, path):                          │
│   1879 │   │   obj = self.subcon._parse(stream, context, path)               │
│   1880 │   │   if obj != self.value:                                         │
│ ❱ 1881 │   │   │   raise ConstError("expected %r but parsed %r" % (self.valu │
│   1882 │   │   return obj                                                    │
│   1883 │   def _build(self, obj, stream, context, path):                     │
│   1884 │   │   if obj not in (None, self.value):                             │
╰──────────────────────────────────────────────────────────────────────────────╯
ConstError: expected 0 but parsed 25

During handling of the above exception, another exception occurred:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ D:\Tools\scripts\dev\devine\devine\commands\dl.py:505 in result              │
│                                                                              │
│    502 │   │   │   │   │   │   │   │   )                                     │
│    503 │   │   │   │   │   │   │   │   for i, track in enumerate(title.track │
│    504 │   │   │   │   │   │   │   )):                                       │
│ ❱  505 │   │   │   │   │   │   │   │   download.result()                     │
│    506 │   │   │   │   except KeyboardInterrupt:                             │
│    507 │   │   │   │   │   console.print(Padding(                            │
│    508 │   │   │   │   │   │   ":x: Download Cancelled...",                  │
│                                                                              │
│ C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \_base.py:438 in result                                                      │
│                                                                              │
│   435 │   │   │   │   if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]: │
│   436 │   │   │   │   │   raise CancelledError()                             │
│   437 │   │   │   │   elif self._state == FINISHED:                          │
│ ❱ 438 │   │   │   │   │   return self.__get_result()                         │
│   439 │   │   │   │                                                          │
│   440 │   │   │   │   self._condition.wait(timeout)                          │
│   441                                                                        │
│                                                                              │
│ C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \_base.py:390 in __get_result                                                │
│                                                                              │
│   387 │   def __get_result(self):                                            │
│   388 │   │   if self._exception:                                            │
│   389 │   │   │   try:                                                       │
│ ❱ 390 │   │   │   │   raise self._exception                                  │
│   391 │   │   │   finally:                                                   │
│   392 │   │   │   │   # Break a reference cycle with the exception in self._ │
│   393 │   │   │   │   self = None                                            │
│                                                                              │
│ C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\concurrent\futures │
│ \thread.py:52 in run                                                         │
│                                                                              │
│    49 │   │   │   return                                                     │
│    50 │   │                                                                  │
│    51 │   │   try:                                                           │
│ ❱  52 │   │   │   result = self.fn(*self.args, **self.kwargs)                │
│    53 │   │   except BaseException as exc:                                   │
│    54 │   │   │   self.future.set_exception(exc)                             │
│    55 │   │   │   # Break a reference cycle with the exception 'exc'         │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\commands\dl.py:860 in download_track      │
│                                                                              │
│    857 │   │   │   │   │   license_widevine=prepare_drm                      │
│    858 │   │   │   │   )                                                     │
│    859 │   │   │   elif track.descriptor == track.Descriptor.MPD:            │
│ ❱  860 │   │   │   │   DASH.download_track(                                  │
│    861 │   │   │   │   │   track=track,                                      │
│    862 │   │   │   │   │   save_path=save_path,                              │
│    863 │   │   │   │   │   save_dir=save_dir,                                │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\manifests\dash.py:369 in             │
│ download_track                                                               │
│                                                                              │
│   366 │   │   │   │   │   ))                                                 │
│   367 │   │   │   │   │   res.raise_for_status()                             │
│   368 │   │   │   │   │   init_data = res.content                            │
│ ❱ 369 │   │   │   │   │   track_kid = track.get_key_id(init_data)            │
│   370 │   │   │   │                                                          │
│   371 │   │   │   │   if segment_timeline is not None:                       │
│   372 │   │   │   │   │   seg_time_list = []                                 │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\tracks\track.py:123 in get_key_id    │
│                                                                              │
│   120 │   │   │   │   │   return UUID(bytes=base64.b64decode(enc_key_id))    │
│   121 │   │                                                                  │
│   122 │   │   # look for track encryption mp4 boxes                          │
│ ❱ 123 │   │   for tenc in get_boxes(init_data, b"tenc"):                     │
│   124 │   │   │   if tenc.key_ID.int != 0:                                   │
│   125 │   │   │   │   return tenc.key_ID                                     │
│   126                                                                        │
│                                                                              │
│ D:\Tools\scripts\dev\devine\devine\core\utilities.py:145 in get_boxes        │
│                                                                              │
│   142 │   │   │   index -= 4  # size is before box type and is 4 bytes long  │
│   143 │   │   data = data[index:]                                            │
│   144 │   │   try:                                                           │
│ ❱ 145 │   │   │   box = Box.parse(data)                                      │
│   146 │   │   except IOError:                                                │
│   147 │   │   │   # TODO: Does this miss any data we may need?               │
│   148 │   │   │   break                                                      │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:175 in │
│ parse                                                                        │
│                                                                              │
│    172 │   │                                                                 │
│    173 │   │   Strings, buffers, memoryviews, and other complete buffers can │
│    174 │   │   """                                                           │
│ ❱  175 │   │   return self.parse_stream(BytesIO(data), context, **kw)        │
│    176 │                                                                     │
│    177 │   def parse_stream(self, stream, context=None, **kw):               │
│    178 │   │   """                                                           │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:186 in │
│ parse_stream                                                                 │
│                                                                              │
│    183 │   │   if context is None:                                           │
│    184 │   │   │   context = Container()                                     │
│    185 │   │   context.update(kw)                                            │
│ ❱  186 │   │   return self._parse(stream, context, "parsing")                │
│    187 │                                                                     │
│    188 │   def _parse(self, stream, context, path):                          │
│    189 │   │   """                                                           │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\pymp4\parser.py:50 in    │
│ _parse                                                                       │
│                                                                              │
│    47 │   │   │   stream.seek(curr_pos)                                      │
│    48 │   │   │   length = eof - curr_pos + lengthfield_size                 │
│    49 │   │   stream2 = BoundBytesIO(stream, length - lengthfield_size)      │
│ ❱  50 │   │   obj = self.subcon._parse(stream2, context, path)               │
│    51 │   │   return obj                                                     │
│    52 │                                                                      │
│    53 │   def _build(self, obj, stream, context, path):                      │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:855 in │
│ _parse                                                                       │
│                                                                              │
│    852 │   │   context = Container(_ = context)                              │
│    853 │   │   for i,sc in enumerate(self.subcons):                          │
│    854 │   │   │   if sc.flagembedded:                                       │
│ ❱  855 │   │   │   │   subobj = list(sc._parse(stream, context, path).items( │
│    856 │   │   │   │   obj.update(subobj)                                    │
│    857 │   │   │   │   context.update(subobj)                                │
│    858 │   │   │   else:                                                     │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:297 in │
│ _parse                                                                       │
│                                                                              │
│    294 │   │   self.subcon = subcon                                          │
│    295 │   │   self._inherit_flags(subcon)                                   │
│    296 │   def _parse(self, stream, context, path):                          │
│ ❱  297 │   │   return self.subcon._parse(stream, context, path)              │
│    298 │   def _build(self, obj, stream, context, path):                     │
│    299 │   │   return self.subcon._build(obj, stream, context, path)         │
│    300 │   def _sizeof(self, context, path):                                 │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:1544   │
│ in _parse                                                                    │
│                                                                              │
│   1541 │   │   self.includekey = includekey                                  │
│   1542 │   def _parse(self, stream, context, path):                          │
│   1543 │   │   key = self.keyfunc(context) if callable(self.keyfunc) else se │
│ ❱ 1544 │   │   obj = self.cases.get(key, self.default)._parse(stream, contex │
│   1545 │   │   if self.includekey:                                           │
│   1546 │   │   │   return key, obj                                           │
│   1547 │   │   else:                                                         │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:859 in │
│ _parse                                                                       │
│                                                                              │
│    856 │   │   │   │   obj.update(subobj)                                    │
│    857 │   │   │   │   context.update(subobj)                                │
│    858 │   │   │   else:                                                     │
│ ❱  859 │   │   │   │   subobj = sc._parse(stream, context, path)             │
│    860 │   │   │   │   if sc.name is not None:                               │
│    861 │   │   │   │   │   obj[sc.name] = subobj                             │
│    862 │   │   │   │   │   context[sc.name] = subobj                         │
│                                                                              │
│ D:\Tools\scripts\dev\devine\.venv\lib\site-packages\construct\core.py:2700   │
│ in _parse                                                                    │
│                                                                              │
│   2697 │   │   except ConstructError as e:                                   │
│   2698 │   │   │   if "\n" in str(e):                                        │
│   2699 │   │   │   │   raise                                                 │
│ ❱ 2700 │   │   │   raise e.__class__("%s\n    %s" % (e, path))               │
│   2701 │   def _build(self, obj, stream, context, path):                     │
│   2702 │   │   try:                                                          │
│   2703 │   │   │   path += " -> %s" % (self.name)                            │
╰──────────────────────────────────────────────────────────────────────────────╯
ConstError: expected 0 but parsed 25
    parsing -> _reserved1

_Originally posted by @Lacanbonda in https://github.com/devine-dl/devine/issues/46#issuecomment-1486191785_

**Comment by rlaphoenix** [comment] 2023-03-28 13:18
Duplicate of #46

**Closed by rlaphoenix** 2023-03-28 13:18 UTC
